# Generated by Django 3.2.5 on 2021-07-26 02:00

from django.db import migrations, models
import django.db.models.deletion
import ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0131_consoleport_speed'),
        ('netbox_plugin_gpon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISPDevice',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=255)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.devicetype')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.manufacturer')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ISPActiveDevice',
            fields=[
                ('ispdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_plugin_gpon.ispdevice')),
                ('ip_address', ipam.fields.IPAddressField(blank=True, default='', null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('netbox_plugin_gpon.ispdevice',),
        ),
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('ispdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_plugin_gpon.ispdevice')),
            ],
            options={
                'abstract': False,
            },
            bases=('netbox_plugin_gpon.ispdevice',),
        ),
    ]
