# Generated by Django 3.2.5 on 2021-07-26 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_plugin_gpon', '0002_ispactivedevice_ispdevice_olt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gponsplitter',
            name='created',
        ),
        migrations.RemoveField(
            model_name='gponsplitter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gponsplitter',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='ispdevice_ptr',
        ),
        migrations.AddField(
            model_name='gponsplitter',
            name='ispdevice_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_plugin_gpon.ispdevice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='olt',
            name='ispactivedevice_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_plugin_gpon.ispactivedevice'),
            preserve_default=False,
        ),
    ]
