# Generated by Django 3.2.5 on 2021-07-26 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_plugin_gpon', '0003_auto_20210726_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONT',
            fields=[
                ('ispactivedevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_plugin_gpon.ispactivedevice')),
                ('uplink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_plugin_gpon.gponsplitter')),
            ],
            options={
                'abstract': False,
            },
            bases=('netbox_plugin_gpon.ispactivedevice',),
        ),
    ]
