# Generated by Django 3.2.5 on 2021-07-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_plugin_gpon', '0004_ont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ispdevice',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
