# Generated by Django 3.2.5 on 2021-08-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_plugin_gpon', '0005_alter_ispdevice_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ispdevice',
            name='uuid',
        ),
    ]
